# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(max_length=100, null=True)),
                ('apellidos', models.CharField(max_length=100, null=True)),
                ('nro_fono', models.CharField(blank=True, max_length=100, null=True)),
                ('edad', models.SmallIntegerField(blank=True, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('genero', models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], default='MASCULINO', max_length=10)),
                ('estado', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
