# Generated by Django 2.1.2 on 2018-10-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appRegister', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='genero',
        ),
        migrations.AddField(
            model_name='persona',
            name='carrera',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nro_fono',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
